# SECRET
# Almacena informacion sensible, como contrasenas de base de datos.
# Los valores deben estar en base64.
# Para codificar: echo -n "valor" | base64

apiVersion: v1
kind: Secret
metadata:
  name: victortorreblanca-secret
  namespace: victortorreblanca
  labels:
    app: microservicios-practica
type: Opaque
data:
  productos-password: UkVFTVBMQVpBUl9QQVNTV09SRF9EQl9QUk9EVUNUT1M=
  pedidos-password: UkVFTVBMQVpBUl9QQVNTV09SRF9EQl9QRURJRE9T
