server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ms-pedidos

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:ep-icy-union-aticzgg0-pooler.c-9.us-east-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:db_pedidos}?sslMode=${DB_SSL_MODE:require}
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD}

servicios:
  productos-url: ${PRODUCTOS_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
